#!/bin/sh
set -e

cat > /opt/app-root/src/config.js << EOF
window.APP_CONFIG = {
  VITE_POLARIS_API_URL: '${VITE_POLARIS_API_URL:-http://localhost:8181}',
  VITE_POLARIS_REALM: '${VITE_POLARIS_REALM:-POLARIS}',
  VITE_POLARIS_PRINCIPAL_SCOPE: '${VITE_POLARIS_PRINCIPAL_SCOPE:-PRINCIPAL_ROLE:ALL}',
  VITE_OAUTH_TOKEN_URL: '${VITE_OAUTH_TOKEN_URL}',
  VITE_POLARIS_REALM_HEADER_NAME: '${VITE_POLARIS_REALM_HEADER_NAME:-Polaris-Realm}',
  VITE_OIDC_ISSUER_URL: '${VITE_OIDC_ISSUER_URL}',
  VITE_OIDC_CLIENT_ID: '${VITE_OIDC_CLIENT_ID}',
  VITE_OIDC_REDIRECT_URI: '${VITE_OIDC_REDIRECT_URI}',
  VITE_OIDC_SCOPE: '${VITE_OIDC_SCOPE}'
};
EOF

exec nginx -g 'daemon off;'
